package ch.epfl.osper.metadata.wikireader;

import ch.epfl.osper.metadata.model.Coordinate;
import ch.epfl.osper.metadata.model.MapLocation;
import ch.epfl.osper.metadata.model.MeasurementLocation;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;
import org.springframework.web.client.RestTemplate;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class LocationEnrichmentServiceTest {

    private  LocationEnrichmentService subject;

    @Mock
    private RestTemplate restTemplateMock;

    @Before
    public void initSubject() throws Exception {
        subject = new LocationEnrichmentService(restTemplateMock);
    }

    @Test
    public void testParsing() throws Exception {
        String result = "<!-- Generated by gsndem/get -->\n" +
                "<!-- Copyright 2014 - 2015 ETH Zurich  -->\n" +
                "<!--\n" +
                "License: Permission is granted ONLY for retrieving elevation information for the locations of the SwissExperiment/OSPER sensors.\n" +
                "Any other use of this Web service is hereby EXPLICITELY FORBIDDEN.\n" +
                "-->\n" +
                "<dem>\n" +
                "<elevation>1976.1</elevation>\n" +
                "<slope>12.634</slope>\n" +
                "<aspect>65.6019</aspect>\n" +
                "</dem>";

        MeasurementLocation measurementLocation = MeasurementLocation.getBuilder()
                .location(new double[]{2.2, 3.3})
                .createMeasurementLocation();
        subject.parseResult(result, measurementLocation);
        assertThat(measurementLocation.getAspect(), is(65.6019));
        assertThat(measurementLocation.getSlope(), is(12.634));
        assertThat(measurementLocation.getElevation(), is(1976.1));
    }
}